//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobSalt.Models.Modules.Jobs.RIT_Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Employers = new HashSet<Employer>();
        }
    
        public int id { get; set; }
        public Nullable<System.Guid> oldId { get; set; }
        public string dce { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string email { get; set; }
        public string title { get; set; }
        public string department { get; set; }
        public string phone { get; set; }
        public string pictureUrl { get; set; }
        public string linkedInUrl { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<System.DateTime> lastActivityDate { get; set; }
    
        public virtual ICollection<Employer> Employers { get; set; }
    }
}
