//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobSalt.Models.Feature.Jobs.RIT_Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public string id { get; set; }
        public int searchableId { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string qualifications { get; set; }
        public string salary { get; set; }
        public Nullable<System.DateTime> postedDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> applicationDate { get; set; }
        public Nullable<int> postedQuarter { get; set; }
        public string archiveStatus { get; set; }
        public string contactId { get; set; }
        public string employerId { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Employer Employer { get; set; }
        public virtual Quarter Quarter { get; set; }
    }
}
