//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobSalt.Models.Feature.Jobs.RIT_Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quarter
    {
        public Quarter()
        {
            this.Jobs = new HashSet<Job>();
        }
    
        public int id { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public string schoolYear { get; set; }
        public string season { get; set; }
    
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
