//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobSalt.Models.Feature.Housing.LocalModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class HousingReview
    {
        public int Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public int Location { get; set; }
        public string Price { get; set; }
        public string Description { get; set; }
        public int Rating { get; set; }
        public string Title { get; set; }
        public string SubmittedBy { get; set; }
    
        public virtual HousingLocation HousingLocation { get; set; }
    }
}
