//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobSalt.Models.Feature.Alumni.School_Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employer
    {
        public string id { get; set; }
        public string name { get; set; }
        public string division { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string website { get; set; }
        public string archiveStatus { get; set; }
        public Nullable<int> accountManagerId { get; set; }
        public string primaryContactId { get; set; }
    }
}
