//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobSalt.Models.Feature.Alumni.School_Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradPlacement
    {
        public int id { get; set; }
        public bool hasAcceptedEmployment { get; set; }
        public bool isAlreadyEmployed { get; set; }
        public bool isAttendingGradSchool { get; set; }
        public bool isFreelancing { get; set; }
        public bool isStillSeeking { get; set; }
        public bool isUndecided { get; set; }
        public bool isNotSeeking { get; set; }
        public string studentUid { get; set; }
        public string studentEmail { get; set; }
        public int studentPrimaryProgramId { get; set; }
        public int studentPrimaryDegreeId { get; set; }
        public Nullable<int> studentSecondaryProgramId { get; set; }
        public string employerName { get; set; }
        public string employerCity { get; set; }
        public string employerStateId { get; set; }
        public string employerCountryId { get; set; }
        public Nullable<bool> hasWorkedForEmployer { get; set; }
        public Nullable<bool> hasCoopedForEmployer { get; set; }
        public Nullable<bool> hasWorkedPartTimeForEmployer { get; set; }
        public Nullable<bool> hasFreelancedForEmployer { get; set; }
        public Nullable<bool> isRelatedToField { get; set; }
        public string placementTitle { get; set; }
        public Nullable<int> placementSalary { get; set; }
        public Nullable<int> placementBonus { get; set; }
        public Nullable<int> placementOriginId { get; set; }
        public string placementOriginOther { get; set; }
        public Nullable<int> freelanceDailyWage { get; set; }
        public string gradSchoolEnrollment { get; set; }
        public string gradSchoolName { get; set; }
        public string gradSchoolProgram { get; set; }
        public string gradSchoolCity { get; set; }
        public string gradSchoolStateId { get; set; }
        public string gradSchoolCountryId { get; set; }
        public string dataSource { get; set; }
        public Nullable<int> dataSourceId { get; set; }
        public string dataSourceOther { get; set; }
        public System.DateTime createdDate { get; set; }
        public System.DateTime modifiedDate { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<int> modifiedBy { get; set; }
        public string notes { get; set; }
        public Nullable<System.DateTime> dateOfferReceived { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<int> numJobOffers { get; set; }
    
        public virtual Program Program { get; set; }
        public virtual Program Program1 { get; set; }
        public virtual Student Student { get; set; }
    }
}
