//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobSalt.Models.Feature.Alumni.School_Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkedInData_
    {
        public double Advance_ID { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip_Code { get; set; }
        public string Phone { get; set; }
        public string Amount { get; set; }
        public string E_Mail_1 { get; set; }
        public string E_Mail_2 { get; set; }
        public Nullable<double> Match_Type { get; set; }
        public string Employer { get; set; }
        public string Employer_Title { get; set; }
        public string Employer_Industry { get; set; }
        public string Employer_Address { get; set; }
        public string Employer_City { get; set; }
        public string Employer_State { get; set; }
        public string Employer_Zip { get; set; }
        public string Employer_Phone { get; set; }
        public string Date { get; set; }
        public string F24 { get; set; }
        public string F25 { get; set; }
        public string UID { get; set; }
    }
}
