//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobSalt.Models.Feature.Alumni.School_Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public Program()
        {
            this.GradPlacements = new HashSet<GradPlacement>();
            this.GradPlacements1 = new HashSet<GradPlacement>();
            this.Students = new HashSet<Student>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string plan { get; set; }
        public string collegeId { get; set; }
        public string name { get; set; }
        public string psName { get; set; }
        public Nullable<bool> requiresCoop { get; set; }
        public Nullable<int> numCoopsRequired { get; set; }
        public bool isSupported { get; set; }
        public bool isDeprecated { get; set; }
        public Nullable<decimal> coopMin { get; set; }
        public Nullable<decimal> coopAvg { get; set; }
        public Nullable<decimal> coopMax { get; set; }
        public Nullable<int> ftMin { get; set; }
        public Nullable<int> ftMed { get; set; }
        public Nullable<int> ftMax { get; set; }
        public System.DateTime createdDate { get; set; }
        public System.DateTime modifiedDate { get; set; }
        public string startingLetter { get; set; }
        public string endingLetter { get; set; }
        public string agreementFormUrl { get; set; }
        public string careerOverviewUrl { get; set; }
        public string coopHandbookUrl { get; set; }
        public string employerHandbookUrl { get; set; }
        public string eventsLinkUrl { get; set; }
        public string onlineResourcesUrl { get; set; }
        public string sampleResumesUrl { get; set; }
        public string symplicityName { get; set; }
        public string symplicityMenuCode { get; set; }
        public int degreeId { get; set; }
    
        public virtual ICollection<GradPlacement> GradPlacements { get; set; }
        public virtual ICollection<GradPlacement> GradPlacements1 { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
